-- ----------------------FROM BACKSIDE ----------------
-- SELECT S.NAME
-- FROM COMPANY C
-- INNER JOIN ORDERS O
--     ON C.COM_ID = O.COM_ID AND C.NAME = "RED"
-- RIGHT JOIN SALESPERSON S
--     ON O.SALES_ID = S.SALES_ID
-- WHERE O.SALES_ID IS NULL;


-- --------------------SUB QUERY -----------------------
SELECT NAME FROM SALESPERSON WHERE SALES_ID NOT IN 
(SELECT O.SALES_ID
FROM ORDERS O
JOIN COMPANY C ON O.COM_ID = C.COM_ID
WHERE C.NAME = "RED");